name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.python }} ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - name: Set up Python ${{ matrix.python }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python }}
        auto-update-conda: true
        channels: conda-forge
        channel-priority: strict
    - name: Install dependencies
      run: |
        conda install setuptools pip wheel build packaging numpy numexpr cython bzip2 hdf5 lzo 'typing_extensions<4.2'
        # conda install sphinx sphinx_rtd_theme numpydoc ipython
    - name: Source distribution
      run: |
        python -m build --sdist
    - name: Installation
      run: |
        pip install -v dist/*.tar.gz
    - name: 'Run test'
      run: |
        cd .. && python -m tables.tests.test_all -v
        pt2to3 -h
        ptrepack -h
        ptdump -h
        pttree -h

